version: '2.1'

volumes:
  graphite_configs:
  graphite_data:

services:
  # graphite:
  #   image: graphiteapp/graphite-statsd
  #   volumes:
  #     - graphite_configs:/opt/graphite/conf
  #     - graphite_data:/opt/graphite/storage
  #   networks:
  #     - openmaptiles_conn
  #   ports:
  #     - "8899:80"

  # artillery:
  #   build:
  #     context: artillery
  #   volumes:
  #     - ./artillery:/artillery
  #   networks:
  #     - openmaptiles_conn

  kartotherian:
    build:
      context: kartotherian
    volumes:
      - ./kartotherian/modules/kartotherian_gl_style_server:/opt/kartotherian/packages/kartotherian/node_modules/kartotherian_gl_style_server
      - ./kartotherian/modules/kartotherian_sources_list_server:/opt/kartotherian/packages/kartotherian/node_modules/kartotherian_sources_list_server
      - ./kartotherian/modules/kartotherian_gl:/opt/kartotherian/packages/kartotherian/node_modules/kartotherian_gl
      - ./kartotherian/config.yaml:/opt/kartotherian/packages/kartotherian/config.yaml
      - ./kartotherian/sources.yaml:/opt/kartotherian/packages/kartotherian/sources.yaml
      - ./openmaptiles/build/openmaptiles.tm2source:/data/openmaptiles.tm2source
      - ./styles:/styles
      - ./fonts:/fonts
      - ./kartotherian/static/public:/opt/kartotherian/packages/server/static
    networks:
      - openmaptiles_conn
    ports:
      - "6533:6533"

  nginx:
    build:
      context: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cache:/cache
      - ./openmaptiles/data/expire_tiles:/data/expire_tiles
    networks:
      - openmaptiles_conn
    ports:
      - "8080:80"

networks:
  openmaptiles_conn:
    name: openmaptiles_postgres_conn
    driver: bridge
