version: '2.1'

services:
  tileserver-gl:
    build:
      context: tileserver-gl/tileserver-gl
    volumes:
      - ./tileserver-gl:/data
      - ./tileserver-gl/tileserver-gl/src:/usr/src/app/src
      - ./tileserver-gl/static/public/index.html:/usr/src/app/public/templates/index.tmpl
      - ./tileserver-gl/static/public:/usr/src/app/public/resources
    networks:
      - openmaptiles_conn

  nginx:
    build:
      context: nginx
    environment:
      - NGINX_DISABLE_CACHE
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/nginx.template.conf:ro
      - ./cache:/cache
      - ./openmaptiles/data/expire_tiles:/data/expire_tiles
    networks:
      - openmaptiles_conn
    ports:
      - "8080:80"

networks:
  openmaptiles_conn:
    name: openmaptiles_postgres_conn
    driver: bridge
