version: '2.1'

volumes:
  pgdata:
    # Avoid droping the database on docker-compose down
    external: true
    name: openmaptiles_pgdata

services:
  postgres:
    image: "openmaptiles/postgis:2.9"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres_conn
    ports:
     - "5432"
    env_file: openmaptiles/.env

  kartotherian:
    build:
      context: kartotherian
    volumes:
      - ./kartotherian/config.yaml:/opt/kartotherian/packages/kartotherian/config.yaml
      - ./kartotherian/sources.yaml:/opt/kartotherian/packages/kartotherian/sources.yaml
      - ./openmaptiles/build/openmaptiles.tm2source:/data/openmaptiles.tm2source
      - ./styles:/styles
    links:
      - postgres
    networks:
      - postgres_conn
    ports:
      - "6533:6533"
    environment:
     - OPENMAPTILES_TILES_URL=${BASE_URL:-http://localhost:6534}/openmaptiles/{z}/{x}/{y}.pbf
     - OPENMAPTILES_TILES_URL_INTERNAL=${BASE_URL:-http://squid:80}/openmaptiles_internal/{z}/{x}/{y}.pbf

  squid:
    image: sameersbn/squid
    hostname: squid
    volumes:
     - ./squid.conf:/etc/squid/squid.conf
     - /tmp/squid-cache:/var/spool/squid
    links:
     - kartotherian
     - tileserver-gl
    networks:
      - postgres_conn
    ports:
      - "6534:80"

networks:
  postgres_conn:
    driver: bridge
