version: '2.1'

services:
  tileserver-gl:
    image: maptiler/tileserver-gl
    volumes:
      - ./tileserver-gl:/data
    networks:
      - openmaptiles_conn

  nginx:
    build:
      context: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cache:/cache
      - ./openmaptiles/data/expire_tiles:/data/expire_tiles
    networks:
      - openmaptiles_conn
    ports:
      - "8080:80"

networks:
  openmaptiles_conn:
    name: openmaptiles_postgres_conn
    driver: bridge
