openmaptiles_v3_source:
  uri: tmsource:///data/openmaptiles.tm2source
  overrideInfo:
    attribution: 'Map data © <a href="http://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

openmaptiles_v3_cache:
  uri: redis://
  params:
    host: redis
    namespace: openmaptiles_v3_cache

openmaptiles_v3:
  public: true
  formats: [pbf]
  uri: cache://
  params:
    source: {ref: openmaptiles_v3_source}
    storage: {ref: openmaptiles_v3_cache}
    http_headers:
      Content-Type: application/x-protobuf
      x-tilelive-contains-data: true
      Content-Encoding: gzip
  overrideInfo:
    Layer:
    _prefs:
    tiles: {var: OPENMAPTILES_V3_TILES_URLS}

# Raster

openmaptiles_v3_raster:
  public: true
  formats: [pbf]
  uri: cache://
  params:
    source: {ref: openmaptiles_v3_source}
    storage: {ref: openmaptiles_v3_cache}
    http_headers:
      Content-Type: application/x-protobuf
      x-tilelive-contains-data: true
      Content-Encoding: gzip
  overrideInfo:
    Layer:
    _prefs:
    tiles: {var: OPENMAPTILES_V3_TILES_URLS_INTERNAL} # Duplicate cache config to change this URL

basic_source:
  uri: kartotherian+gl:///
  params:
    style: basic

basic_cache:
  uri: redis://
  params:
    host: redis
    namespace: basic_cache

basic:
  public: true
  formats: [png, jpeg, webp]
  uri: cache://
  params:
    source: {ref: basic_source}
    storage: {ref: basic_cache}
    http_headers:
      Content-Type: image/png
      x-tilelive-contains-data: true
  overrideInfo:
    tiles: {var: BASIC_TILES_URLS}
