openmaptiles_source:
  uri: tmsource:///data/openmaptiles.tm2source
  overrideInfo:
    attribution: 'Map data © <a href="http://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

# Filter out any small tiles without significant data on or after zoom 10
openmaptiles_substantial:
  uri: substantial://
  params:
    source: {ref: openmaptiles_source}
    minzoom: 10
    minsize: 500
    layers: [water, landuse]

# If tile has been filtered out by substgen, use overzoom to recreate it
openmaptiles:
  public: true
  formats: [pbf]
  uri: overzoom://
  params:
    source: {ref: openmaptiles_substantial}
  overrideInfo:
    tiles: [{env: OPENMAPTILES_TILES_URL}]

openmaptiles_internal:
  public: true
  formats: [pbf]
  uri: overzoom://
  params:
    source: {ref: openmaptiles_substantial}
  overrideInfo:
    tiles: [{env: OPENMAPTILES_TILES_URL_INTERNAL}]

# View tiles as generated directly from the database. Don't view zoom0-5
basic:
  public: true
  formats: [png]
  uri: gl:///styles/klokantech-basic-gl-style/style-internal.json
