openmaptiles_v3_source:
  uri: tmsource:///data/openmaptiles.tm2source
  overrideInfo:
    attribution: 'Map data © <a href="http://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

# Filter out any small tiles without significant data on or after zoom 10
openmaptiles_v3_substantial:
  uri: substantial://
  params:
    source: {ref: openmaptiles_v3_source}
    minzoom: 10
    minsize: 500
    layers: [water, landuse]

# If tile has been filtered out by substgen, use overzoom to recreate it
openmaptiles_v3_overzoom:
  uri: overzoom://
  params:
    source: {ref: openmaptiles_v3_substantial}

openmaptiles_v3_cache:
  uri: redis://
  params:
    host: redis
    namespace: openmaptiles_v3_cache

openmaptiles_v3:
  public: true
  formats: [pbf]
  uri: cache://
  params:
    source: {ref: openmaptiles_v3_overzoom}
    storage: {ref: openmaptiles_v3_cache}
  overrideInfo:
    Layer:
    _prefs:
    tiles: [{env: OPENMAPTILES_V3_TILES_URL}]

# Raster

openmaptiles_v3_raster:
  public: true
  formats: [pbf]
  uri: overzoom:// # Random, just to get an alias
  params:
    source: {ref: openmaptiles_v3}
  overrideInfo:
    tiles: [{env: OPENMAPTILES_V3_TILES_URL_INTERNAL}]

basic_source:
  uri: kartotherian+gl:///
  params:
    style: basic

basic_cache:
  uri: redis://
  params:
    host: redis
    namespace: basic_cache

basic:
  public: true
  formats: [png, jpeg, webp]
  uri: cache://
  params:
    source: {ref: basic_source}
    storage: {ref: basic_cache}
